detectors:
  DuplicateMethodCall:
    enabled: false
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false

directories:
  "app/dashboards":
    UtilityFunction:
      enabled: false
  "db/migrate":
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
