detectors:
  DuplicateMethodCall:
    enabled: false
  InstanceVariableAssumption: # With how Rails uses instance variables in views, this is a false positive too often for me.
    enabled: false
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 10
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false

directories:
  "app/dashboards":
    UtilityFunction:
      enabled: false
  "db/migrate":
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
