---
include:
- "**/*.rb"
exclude: []
require: []
domains: []
plugins: []
reporters:
- rubocop
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
max_files: 5000
