app_version: 0.3.0-preview.3
behavior_configs:
- base_wheel_speed: 16
  hide_cursor_on_click: false
  hide_location: bottom_left
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  multi_action_timeout_ms: 400
  name: behavior_config_1
  tap_threshold_ms: 200
  wheel_mode_auto_off_s: 10
  wheel_speed_multiplier: 4
  wheel_step_size: 100
  wheel_step_size_large: 500
classname: AppConfig
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 2.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  name: grid_config_1
  strategy: subgrid
  subgrid_dims:
  - 5
  - 2
  subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
keymaps:
- entries:
    close dialog: AltRight
    cycle click count: null
    cycle mouse action type: null
    cycle mouse button: null
    edit config: Tab
    execute mouse action: Space
    hide overlay: Escape
    hold for drag: CommandLeft
    hold for move: AltLeft
    hold for right button: CommandRight
    release hold/drag: AltRight
    repeat last mouse action: null
    show overlay: CommandLeft tap
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle overlay: null
  name: keymap_1
monitor_assignments: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.3
  background_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.35
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 1.0
  - 0.5
  - 0.0
  - 0.7
  cursor_move_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 0
  - 1
  - 0.3
  - 0.7
  cursor_right_button_rgba:
  - 1.0
  - 0.3
  - 0.3
  - 0.7
  cursor_size: 7
  font_size_multiplier: 0.75
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  highlight_rgba:
  - 0.5
  - 0.6
  - 7
  - 0.25
  name: style_config_1
  subgrid_font_size_multiplier: 1.0
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.9
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.75
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.75
  text_shadow_blur_radius: 1
  text_shadow_offset:
  - 1
  - -1
  text_shadow_rgba:
  - 0
  - 0
  - 0
  - 0.75
  window_opacity: 1.0
