## General
alias cp="cp -iv"
alias rm="rm -iv"
alias mv="mv -iv"
alias sed="sed -E"
alias help="tldr"
alias n="nvim"
alias cl="clear"
alias src="source ~/.bashrc"
alias bs="brew services"
alias mux="tmuxinator"
alias ms="mux start"
alias home="cd && clear"
## Overrides (Remember that you can run the original command by prepending it with a \. e.g. `\cat` will run the real cat instead of bat.)
alias ls="eza --all --group-directories-first --icons"
alias cat="bat --theme=OneHalfLight"
alias top="htop"
alias find="fd -H"
## Ruby & Rails
alias be="bundle exec"
alias berc="bundle exec rubocop"
alias bepr="bundle exec parallel_rspec"
alias rdm="bundle exec rails db:migrate"
alias rdr="bundle exec rails db:rollback"
alias rdmr="bundle exec rails db:migrate:redo"
alias rdms="bundle exec rails db:migrate:status"
alias tof="bundle exec rspec --format=documentation --only-failures"
alias toof="bundle exec rspec --format=documentation --next-failure"
## Git
alias gco="git checkout"
alias gra="git rebase --abort"
alias gri="git rebase --interactive --autosquash"
alias grc="git rebase --continue"
alias grmaster="git rebase master --interactive --autosquash"
alias grmain="git rebase main --interactive --autosquash"
alias gcf="git commit --fixup"
alias gce="git commit --allow-empty"
alias gcnv="git commit --no-verify"
alias gpsh="git push"
alias gpshf="git push --force-with-lease"
alias gpl="git pull"
alias gs="git stash"
alias gsp="git stash pop"
alias lg="lazygit"
alias wt="git worktree"
alias wtl="git worktree list"
# Claude Code
alias ccc="claude --continue"
alias ccr="claude --resume"
# fzf
alias preview="fzf --preview 'bat --color \"always\" {}'"