#!/bin/sh

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

# Run Rubocop
command_exists bundle exec rubocop && {
  bundle exec rubocop || {
    echo
    echo "Rubocop found some style violations!"
    exit 1
  }
}

# Run RSpec
command_exists bundle exec rspec && {
  bundle exec rspec || {
    echo
    echo "One or more of your RSpec tests failed!"
    exit 1
  }
}
